### ISSUE TITLE
error in XML document

### ISSUE THREAD

**Issue by vicosx12** [hofingerandi/xml2ooxml#1]
[Error](url) when trying to open D:\... .xml: There is an error in XML document (2, 2).
Unhandled exception. System.InvalidOperationException: There is an error in XML document (2, 2).
 ---> System.InvalidOperationException: <AuditFile xmlns='mfp:anaf:dgti:d406:declaratie:v1'> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.X
[D406_14916343_L_2022_1_vol_1.zip](https://github.com/hofingerandi/xml2ooxml/files/10110587/D406_14916343_L_2022_1_vol_1.zip)
mlSerializationReaderConfiguration.Read6_Configuration()

**Comment by hofingerandi** [comment]
The error does not happen during the splitting, but when reading the configuration file. Please check your config for xml-errors, or post the problematic config file here.

**Comment by hofingerandi** [comment]
Cannot reproduce
